### ISSUE TITLE
Memory usage not accurate on Heroku

### ISSUE THREAD

**Issue by schneems** [schneems/get_process_mem#7]
From Heroku:

```
2014-04-07T04:16:14.403204+00:00 app[web.1]: PumaAutoTune (358s): All is well measure#puma.resource_ram_mb=488.5341796875 measure#puma.current_cluster_size=6 measure#puma.max_worker_limit=Infinity
2014-04-07T04:16:15.416413+00:00 heroku[web.1]: source=web.1 dyno=heroku.5385926.fb0a01d2-dbc7-46f1-aae9-d2eddc627596 sample#load_avg_1m=0.15 sample#load_avg_5m=0.06
2014-04-07T04:16:15.416714+00:00 heroku[web.1]: source=web.1 dyno=heroku.5385926.fb0a01d2-dbc7-46f1-aae9-d2eddc627596 sample#memory_total=516.06MB sample#memory_rss=510.52MB sample#memory_cache=0.02MB sample#memory_swap=5.52MB sample#memory_pgpgin=153581pages sample#memory_pgpgout=22883pages
```

Note that `puma.resource_ram_mb=488.5341796875` while `memory_total=516.06`. I can't find docs on the behavior of Pss and whether swap memory gets reported. 

For PumaAutoTune. I'm thinking we'll need to add a fudge factor similar to that in PumaWorkerKiller, though I would like to get this library as accurate as possible.

This may help a bit: https://www.kernel.org/doc/Documentation/filesystems/proc.txt

Related: https://github.com/schneems/puma_auto_tune/issues/9

**Comment by maxrosecollins** [comment]
Has this been fixed yet?

**Comment by schneems** [comment]
> Has this been fixed yet?

It can't really be "fixed" from inside of a container until containers expose that information.

**Comment by fernandokosh** [comment]
And about XEN? Any issues?

**Comment by pratik60** [comment]
@schneems The first line on your readme for puma auto-tune, says don't use until this is fixed. Should we just ignore this and use it?

**Comment by schneems** [comment]
Use at your own risk. I recommend puma worker killer rolling restarts instead.

**Comment by watsonian** [comment]
Just as an update, I was playing around with this some and it appears as though memory usage is accurate *until you start swapping*. After that, it fails to account for the swap and constantly shows up as being below the max memory limit because everything over that is getting swapped out.

As such, if you have a very regular memory leak that happens over the course of several minutes, it should be possible to catch it and restart with a fairly decent level of accuracy so long as you leave enough headroom in the percentage (e.g., 0.9 rather than 0.98) and a short enough frequency.

It's also worth noting that up until Oct 28, 2015, the file system cache was being included in the memory total reported by the platform (see [here](https://devcenter.heroku.com/changelog-items/747)) which could have thrown off the calculation before as well.

**Comment by jjb** [comment]
What about an approach which has an app process its own logs using a middleware?

simplest approach: set up a log drain to send the app's logs back to itself. the middleware picks it up, looks at the memory info, discards everything.

drawbacks:

1) generally  adding complexity to production app
2) adding load to production app (although even with enormous log volume if it's the first middleware i bet it wouldn't affect the app's performance much).
3) log would be posted to random dynos. but luckily each dyno will know which one it is and be able to pick out the appropriate info. so on average a dyno will get its memory info every few minutes at most.

more complicated approach: make standalone app which accepts log drain and nothing else. it filters out the memory info and sends it back to the production app. now the production app just needs to deal with a couple POSTs/minute.

even more complicate: same standalone app above, but instead of sending logs back to production app, the production app can query the standalone app on a schedule. this might offer other interesting opportunities for coordination. although it's getting into territory that is probably anathema to 12-factor.

**Comment by schneems** [comment]
Check out https://github.com/noahd1/oink it sounds similar to that proposal

**Comment by vfreefly** [comment]
@schneems  any reason why PSS was totally deleted? Before the gem had an option which type to choose `GetProcessMem.new(Process.pid, mem_type: 'rss')` (https://github.com/schneems/get_process_mem/tree/edd767cff8a7463e756bac323742e711d445380f). 

There is no problem with PSS. For some processes it's better to use RSS, but for others - PSS. I really don't understand why PSS was deleted.

**Comment by schneems** [comment]
@vfreely this would be a better question for a new issue, it’s not related to the core issue here other than I was using pss to measure. The short answer is that I don’t remember. I think maybe it was because it wasn’t supported in all OSes but I’m not 100% positive.

**Comment by vfreefly** [comment]
@schneems  got it, thanks for answer

**Comment by iGEL** [comment]
@schneems I was wondering whether the recent addition (Docker 1.13, January 2017) of the statistics `/sys/fs/cgroup/memory` might be of use here?

**Comment by schneems** [comment]
Heroku runs on LXC containers do you know if that cgroup interface was implemented there as well?

**Comment by iGEL** [comment]
@schneems No, sorry, I don't know, as we don't use it. However, it would be useful as it seems to become a defacto standard.

In general, this problem applies also to Docker and all other cgroup based containers, doesn't it?

**Comment by schneems** [comment]
The somewhat canonical issue I've been watching is https://github.com/moby/moby/issues/8427#issuecomment-317517504. If that is indeed a defacto standard then I would post there to see what other people think of its use.

**Comment by dush** [comment]
@schneems On Herku there is `/sys/fs/cgroup/memory/memory.limit_in_bytes` which in my case of Hobby dyno reports `536870912` bytes.

**Comment by cesarizu** [comment]
Is this related?

https://help.heroku.com/TWBM7DL0/how-do-i-measure-current-memory-use-and-max-available-memory-on-a-dyno-in-a-private-space

**Comment by schneems** [comment]
Kinda, but get_process_mem's job is to find the memory of a specific process while that file tells us the memory of the whole system. We could maybe add helper methods like `GetProcessMem.heroku_private_space_mem` and `GetProcessMem.heroku_private_space?` (so we can know when we're in a private space), i'm not sure what the cannonical way of knowing is, though I guess presence of that file would be a pretty good indication.

**Comment by ioquatix** [comment]
@schneems How does Heroku determine the space used by a container?

**Comment by schneems** [comment]
> How does Heroku determine the space used by a container?

It's reported externally to the host OS. We don't document the exact mechanism anywhere.

I want to close this issue in the interest of cleaning up issues. It's a much bigger problem than can be solved in just this thread.

**Comment by vhermecz** [comment]
I was happy to see that finally a repo which has no open issues.
I was sad to realize, that this issues has been closed despite it is still an issue.
This gem reports 1.55GB while heroku metrics show around 6.5GB usage.
Would be nice to mention it somewhere that Heroku is problematic.
Sorry for the noise here, process memory usage is not an easy area, thanks for maintaining this gem!
